export { default as RegisterDashboard } from './RegisterDashboard'
export {default as RegisterActive} from './RegisterActive'
export {default as RegisterHome} from './RegisterHome'
export {default as RegisterHostel} from './RegisterHostel'
export {default as RegisterPayment} from './RegisterPayment'
export {default as RegisterProfile} from './RegisterProfile'
export {default as RegisterRefund} from './RegisterRefund'
export {default as StudentsRegister} from './StudentsRegister'
export {default as StudentStatusManager} from './StudentStatusManager'
export {default as PrivilegedRegister} from './PrivilegedRegister'
export {default as RegisterMessage} from './RegisterMessage'
export {default as AttandanseSunday} from './AttandanseSunday'
export {default as UpdateStudent} from './form/UpdateStudent'
export {default as StudentListRegister} from './StudentListRegister'
export {default as MonthlyPaymentControl} from './MonthlyPaymentControl'
export {default as StudentActive} from './StudentActive'